### ISSUE TITLE
A user can view another user's picture and see who liked it.

### ISSUE THREAD

**Issue by LiamBurchellReyes** [JosephMezza/SOEN341#67]
User Story:
User can view another user's profile which displays all of that user's posts. Those posts have their own pages, with a like counter that displays everyone who liked it.

**Comment by LiamBurchellReyes** [comment]
Note: much of the functionality of this user story has already been implemented. Sprint 4 is mainly reserved for Exception Handling and Bug-fixing.

**Comment by LiamBurchellReyes** [comment]
Add-on: Sprint 4 is also reserved for transferring the database from .csv files to an online database.

**Comment by JosephMezza** [comment]
Acceptance Test: PASS
![image](https://user-images.githubusercontent.com/60296506/114809247-d1b68180-9d77-11eb-9de1-ae3ad974a660.png)
