### ISSUE TITLE
A user can go on a person's profile and see their pictures and followers

### ISSUE THREAD

**Issue by alexbara2000** [JosephMezza/SOEN341#82]
User story:
A user can click on a person's profile and get redirected to their page where they can see all the people that person follows and all the people that follow them as well as all of their picutres.

**Comment by JosephMezza** [comment]
Acceptance Test: PASS
![image](https://user-images.githubusercontent.com/60296506/114808925-37563e00-9d77-11eb-87f4-3dc7d6eb30a0.png)
