### ISSUE TITLE
A user can follow another user and see their pictures

### ISSUE THREAD

**Issue by alexbara2000** [JosephMezza/SOEN341#84]
User story:
As a user, I can follow any other user I want and their pictures will appear on my main page. If someone follows me, they will also see my pictures on their home page.

**Comment by JosephMezza** [comment]
Acceptance Test: PASS
![image](https://user-images.githubusercontent.com/60296506/114808466-50122400-9d76-11eb-8f68-0ab1c7ef3877.png)
