### ISSUE TITLE
A user can upload a picture along with a caption for other users to see

### ISSUE THREAD

**Issue by JosephMezza** [JosephMezza/SOEN341#9]
User Story:
User can select a photo from their library and write a caption that will be included right under the picture for followers to see.

**Comment by LiamBurchellReyes** [comment]
Note: To be continued in Sprint 3.

**Comment by JosephMezza** [comment]
Acceptance test: PASS
![image](https://user-images.githubusercontent.com/60296506/114606503-55357d00-9c69-11eb-9feb-36d1cdef4a48.png)
